### ISSUE TITLE
Zren fork of Dolphin

### ISSUE THREAD

**Issue by pavbaranov** [polaur/repo-refreshed#7]
There is Zren fork of Dolphin: https://github.com/Zren/dolphin
Here are his patches: https://github.com/KDE/dolphin/compare/master...Zren:zren
What do you think - should we use all or some of them to our dolphin?

**Comment by worldofpeace** [comment]
Did a quick look and there's some issues fixed that annoyed me that I didn't even know about.
Will definitely be looking into this.

**Comment by worldofpeace** [comment]
@pavbaranov 
Having trouble getting these to work...

**Comment by pavbaranov** [comment]
I haven't tested them yet. Must see.

2018-03-21 0:07 GMT+01:00 worldofpeace <notifications@github.com>:
